/*
 * generated by Xtext 2.11.0
 */
package com.itemis.jbc.ui.contentassist


/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class JBCProposalProvider extends AbstractJBCProposalProvider {
}
